export interface MuhuratItem {
  id: string
  year: number
  month: string
  event: string
  date: string
  day: string
  timing: string
  nakshatra: string
  tithi: string
  specialNotes: string
}

export const SHUBH_MUHURAT_DATA: MuhuratItem[] = [
  {
    id: 'muhurat-1',
    year: 2026,
    month: 'January',
    event: 'Vivah Muhurat',
    date: '16 Jan 2026',
    day: 'Friday',
    timing: '07:15 AM - 02:45 PM',
    nakshatra: 'Rohini',
    tithi: 'Tritiya',
    specialNotes: 'Shukla Paksha',
  },
  {
    id: 'muhurat-2',
    year: 2026,
    month: 'January',
    event: 'Griha Pravesh',
    date: '22 Jan 2026',
    day: 'Thursday',
    timing: '08:20 AM - 11:50 AM',
    nakshatra: 'Uttara Bhadrapada',
    tithi: 'Panchami',
    specialNotes: 'Shubha Lagna',
  },
  {
    id: 'muhurat-3',
    year: 2026,
    month: 'January',
    event: 'Vahan Khareedi',
    date: '25 Jan 2026',
    day: 'Sunday',
    timing: '07:12 AM - 05:30 PM',
    nakshatra: 'Aswini',
    tithi: 'Ashtami',
    specialNotes: 'Ravi Yoga',
  },
  {
    id: 'muhurat-4',
    year: 2026,
    month: 'February',
    event: 'Vivah Muhurat',
    date: '04 Feb 2026',
    day: 'Wednesday',
    timing: '08:00 PM - 06:15 AM (5 Feb)',
    nakshatra: 'Magha',
    tithi: 'Dwitiya',
    specialNotes: 'Ravi Yoga',
  },
  {
    id: 'muhurat-5',
    year: 2026,
    month: 'February',
    event: 'Mundan Muhurat',
    date: '12 Feb 2026',
    day: 'Thursday',
    timing: '09:10 AM - 01:30 PM',
    nakshatra: 'Uttara Phalguni',
    tithi: 'Dashami',
    specialNotes: 'Shubha Tithi',
  },
  {
    id: 'muhurat-6',
    year: 2026,
    month: 'February',
    event: 'Griha Pravesh',
    date: '19 Feb 2026',
    day: 'Thursday',
    timing: '06:55 AM - 10:15 AM',
    nakshatra: 'Anuradha',
    tithi: 'Tritiya',
    specialNotes: 'Amrit Siddhi Yoga',
  },
  {
    id: 'muhurat-7',
    year: 2026,
    month: 'March',
    event: 'Property Khareedi',
    date: '05 Mar 2026',
    day: 'Thursday',
    timing: '06:40 AM - 03:20 PM',
    nakshatra: 'Swati',
    tithi: 'Dwitiya',
    specialNotes: 'Shubh Yoga',
  },
  {
    id: 'muhurat-8',
    year: 2026,
    month: 'March',
    event: 'Naamkaran Muhurat',
    date: '18 Mar 2026',
    day: 'Wednesday',
    timing: '07:00 AM - 12:00 PM',
    nakshatra: 'Rohini',
    tithi: 'Amavasya / Pratipada',
    specialNotes: 'Shubha Nakshatra',
  },
  {
    id: 'muhurat-9',
    year: 2026,
    month: 'April',
    event: 'Vivah Muhurat',
    date: '18 Apr 2026',
    day: 'Saturday',
    timing: '06:00 PM - 04:30 AM (19 Apr)',
    nakshatra: 'Rohini',
    tithi: 'Tritiya',
    specialNotes: 'Akshaya Tritiya Shubh',
  },
  {
    id: 'muhurat-10',
    year: 2026,
    month: 'April',
    event: 'Griha Pravesh',
    date: '25 Apr 2026',
    day: 'Saturday',
    timing: '05:45 AM - 11:20 AM',
    nakshatra: 'Pushya',
    tithi: 'Navami',
    specialNotes: 'Sarvartha Siddhi Yoga',
  },
  {
    id: 'muhurat-11',
    year: 2026,
    month: 'May',
    event: 'Vivah Muhurat',
    date: '02 May 2026',
    day: 'Saturday',
    timing: '07:30 PM - 05:15 AM (3 May)',
    nakshatra: 'Anuradha',
    tithi: 'Dwitiya',
    specialNotes: 'Shubha Lagna',
  },
  {
    id: 'muhurat-12',
    year: 2026,
    month: 'June',
    event: 'Vahan Khareedi',
    date: '11 Jun 2026',
    day: 'Thursday',
    timing: '05:25 AM - 08:40 PM',
    nakshatra: 'Hasta',
    tithi: 'Ekadashi',
    specialNotes: 'Ravi Yoga',
  },
  {
    id: 'muhurat-13',
    year: 2026,
    month: 'November',
    event: 'Vivah Muhurat',
    date: '21 Nov 2026',
    day: 'Saturday',
    timing: '06:45 PM - 06:10 AM (22 Nov)',
    nakshatra: 'Rohini',
    tithi: 'Dwitiya',
    specialNotes: 'Dev Uthani Ekadashi Ke Baad',
  },
  {
    id: 'muhurat-14',
    year: 2026,
    month: 'December',
    event: 'Griha Pravesh',
    date: '10 Dec 2026',
    day: 'Thursday',
    timing: '07:05 AM - 01:15 PM',
    nakshatra: 'Uttara Ashadha',
    tithi: 'Pratipada',
    specialNotes: 'Shubh Nakshatra',
  },
  {
    id: 'muhurat-15',
    year: 2027,
    month: 'January',
    event: 'Vahan Khareedi',
    date: '18 Jan 2027',
    day: 'Monday',
    timing: '07:15 AM - 04:00 PM',
    nakshatra: 'Rohini',
    tithi: 'Ekadashi',
    specialNotes: 'Sarvartha Siddhi Yoga',
  },
  {
    id: 'muhurat-16',
    year: 2027,
    month: 'February',
    event: 'Vivah Muhurat',
    date: '08 Feb 2027',
    day: 'Monday',
    timing: '07:00 PM - 06:30 AM (9 Feb)',
    nakshatra: 'Uttara Phalguni',
    tithi: 'Tritiya',
    specialNotes: 'Shubh Lagna',
  },
  {
    id: 'muhurat-17',
    year: 2027,
    month: 'March',
    event: 'Property Khareedi',
    date: '12 Mar 2027',
    day: 'Friday',
    timing: '06:30 AM - 02:45 PM',
    nakshatra: 'Anuradha',
    tithi: 'Panchami',
    specialNotes: 'Ravi Yoga',
  },
  {
    id: 'muhurat-18',
    year: 2027,
    month: 'April',
    event: 'Griha Pravesh',
    date: '09 Apr 2027',
    day: 'Friday',
    timing: '06:05 AM - 11:50 AM',
    nakshatra: 'Krittika',
    tithi: 'Tritiya',
    specialNotes: 'Akshaya Tritiya',
  },
  {
    id: 'muhurat-19',
    year: 2027,
    month: 'May',
    event: 'Vivah Muhurat',
    date: '15 May 2027',
    day: 'Saturday',
    timing: '08:15 PM - 05:00 AM (16 May)',
    nakshatra: 'Hasta',
    tithi: 'Dashami',
    specialNotes: 'Shubha Tithi',
  },
  {
    id: 'muhurat-20',
    year: 2027,
    month: 'June',
    event: 'Mundan Muhurat',
    date: '17 Jun 2027',
    day: 'Thursday',
    timing: '05:25 AM - 11:30 AM',
    nakshatra: 'Pushya',
    tithi: 'Trayodashi',
    specialNotes: 'Shubh Nakshatra',
  },
  {
    id: 'muhurat-21',
    year: 2027,
    month: 'November',
    event: 'Vivah Muhurat',
    date: '25 Nov 2027',
    day: 'Thursday',
    timing: '06:50 PM - 06:20 AM (26 Nov)',
    nakshatra: 'Rohini',
    tithi: 'Dwitiya',
    specialNotes: 'Shubh Mahurat',
  },
  {
    id: 'muhurat-22',
    year: 2027,
    month: 'December',
    event: 'Griha Pravesh',
    date: '15 Dec 2027',
    day: 'Wednesday',
    timing: '07:08 AM - 12:40 PM',
    nakshatra: 'Uttara Bhadrapada',
    tithi: 'Saptami',
    specialNotes: 'Amrit Siddhi Yoga',
  },
  {
    id: 'muhurat-23',
    year: 2028,
    month: 'January',
    event: 'Naamkaran Muhurat',
    date: '20 Jan 2028',
    day: 'Thursday',
    timing: '07:14 AM - 01:00 PM',
    nakshatra: 'Aswini',
    tithi: 'Navami',
    specialNotes: 'Shubh Tithi',
  },
  {
    id: 'muhurat-24',
    year: 2028,
    month: 'February',
    event: 'Vivah Muhurat',
    date: '11 Feb 2028',
    day: 'Friday',
    timing: '07:10 PM - 06:40 AM (12 Feb)',
    nakshatra: 'Anuradha',
    tithi: 'Panchami',
    specialNotes: 'Shubh Lagna',
  },
  {
    id: 'muhurat-25',
    year: 2028,
    month: 'April',
    event: 'Griha Pravesh',
    date: '28 Apr 2028',
    day: 'Friday',
    timing: '05:42 AM - 10:30 AM',
    nakshatra: 'Rohini',
    tithi: 'Tritiya',
    specialNotes: 'Akshaya Tritiya Shubh',
  },
  {
    id: 'muhurat-26',
    year: 2028,
    month: 'May',
    event: 'Vivah Muhurat',
    date: '06 May 2028',
    day: 'Saturday',
    timing: '06:30 PM - 05:10 AM (7 May)',
    nakshatra: 'Hasta',
    tithi: 'Dwitiya',
    specialNotes: 'Sarvartha Siddhi Yoga',
  },
  {
    id: 'muhurat-27',
    year: 2028,
    month: 'June',
    event: 'Vahan Khareedi',
    date: '15 Jun 2028',
    day: 'Thursday',
    timing: '05:23 AM - 07:15 PM',
    nakshatra: 'Pushya',
    tithi: 'Navami',
    specialNotes: 'Ravi Yoga',
  },
  {
    id: 'muhurat-28',
    year: 2028,
    month: 'November',
    event: 'Vivah Muhurat',
    date: '19 Nov 2028',
    day: 'Sunday',
    timing: '06:45 PM - 06:05 AM (20 Nov)',
    nakshatra: 'Uttara Phalguni',
    tithi: 'Dwitiya',
    specialNotes: 'Dev Uthani Paschat',
  },
  {
    id: 'muhurat-29',
    year: 2028,
    month: 'December',
    event: 'Property Khareedi',
    date: '08 Dec 2028',
    day: 'Friday',
    timing: '07:02 AM - 03:00 PM',
    nakshatra: 'Anuradha',
    tithi: 'Saptami',
    specialNotes: 'Shubha Yoga',
  },
  {
    id: 'muhurat-30',
    year: 2029,
    month: 'January',
    event: 'Griha Pravesh',
    date: '24 Jan 2029',
    day: 'Wednesday',
    timing: '07:12 AM - 11:45 AM',
    nakshatra: 'Uttara Ashadha',
    tithi: 'Navami',
    specialNotes: 'Sarvartha Siddhi Yoga',
  },
  {
    id: 'muhurat-31',
    year: 2029,
    month: 'February',
    event: 'Vivah Muhurat',
    date: '03 Feb 2029',
    day: 'Saturday',
    timing: '07:20 PM - 06:35 AM (4 Feb)',
    nakshatra: 'Rohini',
    tithi: 'Panchami',
    specialNotes: 'Shubh Lagna',
  },
  {
    id: 'muhurat-32',
    year: 2029,
    month: 'March',
    event: 'Mundan Muhurat',
    date: '15 Mar 2029',
    day: 'Thursday',
    timing: '06:30 AM - 12:15 PM',
    nakshatra: 'Aswini',
    tithi: 'Dashami',
    specialNotes: 'Shubha Tithi',
  },
  {
    id: 'muhurat-33',
    year: 2029,
    month: 'April',
    event: 'Vivah Muhurat',
    date: '20 Apr 2029',
    day: 'Friday',
    timing: '06:00 PM - 05:25 AM (21 Apr)',
    nakshatra: 'Anuradha',
    tithi: 'Saptami',
    specialNotes: 'Shubh Muhurat',
  },
  {
    id: 'muhurat-34',
    year: 2029,
    month: 'May',
    event: 'Griha Pravesh',
    date: '17 May 2029',
    day: 'Thursday',
    timing: '05:30 AM - 10:10 AM',
    nakshatra: 'Rohini',
    tithi: 'Panchami',
    specialNotes: 'Amrit Siddhi Yoga',
  },
  {
    id: 'muhurat-35',
    year: 2029,
    month: 'November',
    event: 'Vivah Muhurat',
    date: '18 Nov 2029',
    day: 'Sunday',
    timing: '06:42 PM - 06:12 AM (19 Nov)',
    nakshatra: 'Uttara Phalguni',
    tithi: 'Tritiya',
    specialNotes: 'Shubha Lagna',
  },
  {
    id: 'muhurat-36',
    year: 2029,
    month: 'December',
    event: 'Vahan Khareedi',
    date: '12 Dec 2029',
    day: 'Wednesday',
    timing: '07:05 AM - 05:00 PM',
    nakshatra: 'Pushya',
    tithi: 'Ekadashi',
    specialNotes: 'Ravi Yoga',
  },
  {
    id: 'muhurat-37',
    year: 2030,
    month: 'January',
    event: 'Vivah Muhurat',
    date: '17 Jan 2030',
    day: 'Thursday',
    timing: '07:15 PM - 06:45 AM (18 Jan)',
    nakshatra: 'Rohini',
    tithi: 'Trayodashi',
    specialNotes: 'Shubh Muhurat',
  },
  {
    id: 'muhurat-38',
    year: 2030,
    month: 'February',
    event: 'Griha Pravesh',
    date: '14 Feb 2030',
    day: 'Thursday',
    timing: '07:00 AM - 12:20 PM',
    nakshatra: 'Uttara Bhadrapada',
    tithi: 'Ekadashi',
    specialNotes: 'Sarvartha Siddhi Yoga',
  },
  {
    id: 'muhurat-39',
    year: 2030,
    month: 'April',
    event: 'Property Khareedi',
    date: '11 Apr 2030',
    day: 'Thursday',
    timing: '06:00 AM - 02:15 PM',
    nakshatra: 'Hasta',
    tithi: 'Panchami',
    specialNotes: 'Ravi Yoga',
  },
  {
    id: 'muhurat-40',
    year: 2030,
    month: 'May',
    event: 'Vivah Muhurat',
    date: '01 May 2030',
    day: 'Wednesday',
    timing: '06:15 PM - 05:15 AM (2 May)',
    nakshatra: 'Anuradha',
    tithi: 'Tritiya',
    specialNotes: 'Akshaya Tritiya Shubh',
  },
  {
    id: 'muhurat-41',
    year: 2030,
    month: 'June',
    event: 'Mundan Muhurat',
    date: '13 Jun 2030',
    day: 'Thursday',
    timing: '05:23 AM - 11:00 AM',
    nakshatra: 'Pushya',
    tithi: 'Dashami',
    specialNotes: 'Shubha Tithi',
  },
  {
    id: 'muhurat-42',
    year: 2030,
    month: 'November',
    event: 'Vivah Muhurat',
    date: '22 Nov 2030',
    day: 'Friday',
    timing: '06:48 PM - 06:20 AM (23 Nov)',
    nakshatra: 'Rohini',
    tithi: 'Dwitiya',
    specialNotes: 'Dev Uthani Paschat',
  },
  {
    id: 'muhurat-43',
    year: 2030,
    month: 'December',
    event: 'Griha Pravesh',
    date: '18 Dec 2030',
    day: 'Wednesday',
    timing: '07:10 AM - 01:00 PM',
    nakshatra: 'Uttara Ashadha',
    tithi: 'Saptami',
    specialNotes: 'Shubh Nakshatra',
  },
]

export const MUHURAT_EVENT_TYPES = [
  'All',
  'Vivah Muhurat',
  'Griha Pravesh',
  'Vahan Khareedi',
  'Mundan Muhurat',
  'Naamkaran Muhurat',
  'Property Khareedi',
]

export const MUHURAT_YEARS = ['All', 2026, 2027, 2028, 2029, 2030]

export const MUHURAT_MONTHS = [
  'All',
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
]
