export const STATIC_TOOLS = [
  {
    id: 'static-kundali',
    name: 'Free Kundali (Birth Chart)',
    slug: 'kundali',
    description: 'Generate your detailed Vedic birth chart with planetary positions, doshas, and predictions.',
    isActive: true,
    isFree: true,
    price: 0,
    trialDays: 0,
    features: ['Detailed Birth Chart', 'Planetary Positions', 'Mangal Dosha Check'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'static-panchang',
    name: 'Today\'s Panchang',
    slug: 'panchang',
    description: 'Check daily Hindu calendar with Tithi, Nakshatra, Yoga, Karana, and auspicious timings.',
    isActive: true,
    isFree: true,
    price: 0,
    trialDays: 0,
    features: ['Daily Tithi', 'Auspicious Timings', 'Rahukaal'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'static-milan',
    name: 'Kundali Milan',
    slug: 'milan',
    description: 'Check compatibility for marriage with detailed Ashtakoot Guna Milan analysis.',
    isActive: true,
    isFree: false,
    price: 199,
    trialDays: 1,
    features: ['Ashtakoot Guna Milan', 'Manglik Compatibility', 'Detailed Conclusion'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'static-muhurat',
    name: 'Auspicious Muhurat',
    slug: 'muhurat',
    description: 'Find the most auspicious time (Shubh Muhurat) for marriage, vehicle purchase, and events.',
    isActive: true,
    isFree: false,
    price: 99,
    trialDays: 1,
    features: ['Marriage Muhurat', 'Griha Pravesh', 'Vehicle Purchase'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
